@host=http://localhost
@port=1239

###
POST {{host}}:{{port}}/auth/send-code HTTP/1.1
content-type: application/json

{
  "email": "vitoraraujo1694@gmail.com"
}

###
POST {{host}}:{{port}}/auth/verify-code HTTP/1.1
content-type: application/json

{
  "email": "vitoraraujo1694@gmail.com",
  "code": "401824"
}
