###
POST http://localhost:1239/auth/send-code HTTP/1.1
content-type: application/json

{
  "email": "vitoraraujo1694@gmail.com"
}

###
POST http://localhost:1239/auth/verify-code HTTP/1.1
content-type: application/json

{
  "email": "vitoraraujo1694@gmail.com",
  "code": "866126"
}
