@host=http://localhost
@port=1239

###
GET {{host}}:{{port}}/users/95efbd6e-2908-4535-a909-86fa2e9ed428

###
GET {{host}}:{{port}}/users/email?email=vitoraraujo1694%40gmail.com

###
PATCH {{host}}:{{port}}/users/95efbd6e-2908-4535-a909-86fa2e9ed428/status
Content-Type: application/json

{
  "active": true
}