@host=http://localhost
@port=1239

### Get payment methods of the user
GET {{host}}:{{port}}/users/664c7094-363c-4ad0-a1f8-a7212ea2fd2d/payment-methods

### Create a new payment method for the user
POST {{host}}:{{port}}/users/664c7094-363c-4ad0-a1f8-a7212ea2fd2d/payment-methods
Content-Type: application/json

{
  "name": "Itaú",
  "type": "TED",
  "paymentAt": null,
  "closingAt": null,
  "enabled": true
}

### Delete payment methods of the user
DELETE {{host}}:{{port}}/users/664c7094-363c-4ad0-a1f8-a7212ea2fd2d/payment-methods/b23588bd-8295-4944-9d16-ffa434c0e921

### Update a payment method for the user
PATCH {{host}}:{{port}}/users/664c7094-363c-4ad0-a1f8-a7212ea2fd2d/payment-methods/b23588bd-8295-4944-9d16-ffa434c0e921
Content-Type: application/json

{
  "name": "BTG",
  "type": "CREDIT_CARD",
  "paymentAt": 6,
  "closingAt": 26,
  "enabled": true
}