###
GET http://localhost:1239/users/95efbd6e-2908-4535-a909-86fa2e9ed428

###
GET http://localhost:1239/users/email?email=vitoraraujo1694%40gmail.com

###
PATCH http://localhost:1239/users/95efbd6e-2908-4535-a909-86fa2e9ed428/status
Content-Type: application/json

{
  "active": true
}