@host=http://localhost
@port=1239

### Get profile of the user
GET {{host}}:{{port}}/users/664c7094-363c-4ad0-a1f8-a7212ea2fd2d/profile

### Update the profile of the user
PATCH {{host}}:{{port}}/users/664c7094-363c-4ad0-a1f8-a7212ea2fd2d/profile
Content-Type: application/json

{
  "displayName": "Vitor",
  "bio": "Olá, eu sou o Vitor Araujo!"
}
